In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
lst=[1,2,3,'anshu']
lst

[1, 2, 3, 'anshu']

In [4]:
arr1=np.array(lst)

In [5]:
arr1

array(['1', '2', '3', 'anshu'], dtype='<U21')

In [6]:
lst2=[[1,2,3,'anshu'],[2,3,4,'kripa']]
lst2

[[1, 2, 3, 'anshu'], [2, 3, 4, 'kripa']]

In [7]:

np.array(lst2)

array([['1', '2', '3', 'anshu'],
       ['2', '3', '4', 'kripa']], dtype='<U21')

In [8]:
lst2

[[1, 2, 3, 'anshu'], [2, 3, 4, 'kripa']]

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(1,20,5,endpoint=True)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

# Random Numbers Generations 

In [18]:
np.random.randint(1,20,10)

array([ 3,  8, 14, 12,  7, 16,  5, 16, 12, 18], dtype=int32)

In [19]:
np.random.randint(2,100,100)

array([55, 44, 81, 75, 20, 35,  5, 91, 63, 93, 40, 47, 46, 46,  6, 70, 30,
       51, 80, 84, 14, 70,  5, 19, 54,  8, 73, 76, 77, 22, 73,  7, 60, 65,
       42, 55, 11, 68, 21, 92, 15, 17, 16, 76, 19,  4, 27, 74, 94, 67, 86,
       96, 86, 57, 56, 39, 42, 41, 33, 69, 87, 67, 20, 97, 13, 81, 33, 71,
       78, 26, 79, 15, 19, 40, 20,  8,  6, 70, 33,  9, 91, 24, 59, 63, 20,
       44, 28,  2, 85, 52, 42, 81, 56, 54, 88, 92, 28, 98, 84, 74],
      dtype=int32)

In [20]:
np.random.rand(5)

array([0.74440778, 0.93934825, 0.1472829 , 0.41458856, 0.52088401])

In [21]:
np.random.rand(2,3)

array([[0.08664982, 0.29759636, 0.4041831 ],
       [0.20269753, 0.30353933, 0.93107226]])

In [22]:
np.random.randn(4) # this is with the normal distribution where as the prior was with the standard distribution 

array([-1.37336477, -1.87964902,  0.00951498, -1.41980755])

In [23]:
arr= np.arange(1,21).reshape(5,4)

In [24]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [25]:
arr.shape
arr.size

20

In [26]:
arr.shape

(5, 4)

In [27]:
arr.shape

(5, 4)

In [28]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [29]:
arr.max()

np.int64(20)

In [30]:
kripa = arr.min()
kripa


np.int64(1)

In [31]:
flatted= arr.flatten()

In [32]:
anshu=flatted[19]
anshu

np.int64(20)

In [33]:

arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
arr.sum()

np.int64(210)

In [35]:
np.sum(arr)

np.int64(210)

In [36]:

np.sum(arr,axis=0)

array([45, 50, 55, 60])

In [37]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [38]:

arr.reshape((5,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [40]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [41]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [51]:
arr1=np.arange(1,21).reshape((4,5))
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
arr1.argmax()

np.int64(19)

In [57]:
flat=arr1.flatten()

In [58]:
flat[19]

np.int64(20)

In [59]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [60]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
np.argwhere(arr1==8)

array([[1, 2]])

In [63]:
np.argwhere(flat==13)

array([[12]])

In [64]:
flat[12]

np.int64(13)

In [65]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
arr1[0]

array([1, 2, 3, 4, 5])

In [67]:
arr1[0,0]

np.int64(1)

In [68]:
np.argwhere(arr1==8)

array([[1, 2]])

In [69]:
arr1[1,2]

np.int64(8)

In [70]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [71]:
arr[:,2]

array([ 3,  7, 11, 15, 19])

In [72]:
anshu= arr1 % 2 ==0 
anshu

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [73]:
arr1=arr1[anshu]

In [74]:
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
arr1=np.arange(0,16).reshape((4,4))

In [89]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
arr3=arr1

In [85]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
arr3=arr1.copy()

In [87]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
anshu= np.arange(1,17).reshape((4,4))

In [93]:
anshu

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
arr3=anshu

In [96]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [97]:
anshu

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [98]:
anshu=arr3

In [99]:
anshu

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [101]:
arr3=arr3 -20
arr3

array([[-19, -18, -17, -16],
       [-15, -14, -13, -12],
       [-11, -10,  -9,  -8],
       [ -7,  -6,  -5,  -4]])

In [103]:
arr3 @ anshu

array([[-470, -540, -610, -680],
       [-358, -412, -466, -520],
       [-246, -284, -322, -360],
       [-134, -156, -178, -200]])

In [104]:
anshu.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [108]:
np.reshape(np.arange(12),(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
anshu.ndim

2

In [110]:
anshu

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])