In [1]:
import numpy as np

In [2]:
myarr= np.array([3,4,5,51233],np.int64)

In [3]:
myarr[3]

np.int64(51233)

In [4]:
myarr2=np.array([[2,3,4,5,6,6]])

In [5]:
myarr2[0,1]

np.int64(3)

In [6]:
myarr.shape

(4,)

In [7]:
myarr2.shape

(1, 6)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
myarr

array([    3,     4,     5, 51233])

In [10]:
myarr[1]

np.int64(4)

In [11]:
myarr[1]=100

In [12]:
myarr

array([    3,   100,     5, 51233])

In [13]:
myarr.shape

(4,)

In [14]:
anshu = np.arange(1,10,2)

In [15]:
anshu

array([1, 3, 5, 7, 9])

In [16]:
ls= np.linspace(1,5,12)

In [17]:
ls

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
ls.size

12

In [19]:
ls.shape

(12,)

In [20]:
kripa = np.empty((2,3))

In [21]:
print(kripa)

[[3.03422844e-086 7.70029741e+175 5.03128777e+180]
 [5.27486439e-091 1.04987629e-153 8.07846605e-013]]


In [22]:
print(np.empty((3,2)))

[[3.03422844e-086 7.70029741e+175]
 [5.03128777e+180 5.27486439e-091]
 [1.04987629e-153 8.07846605e-013]]


In [23]:
keipa2= np.empty_like(myarr)

In [24]:
keipa2


array([            0, 1596286613392, 1596286612112, 1596286613072])

In [25]:
ide= np.identity(3)

In [26]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
ide.shape

(3, 3)

In [28]:
ide.size

9

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.reshape(33,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [34]:
arr = arr.ravel()

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

In [37]:
x= [[1,2,3],[4,5,6],[1,1,0]]

In [38]:
ar= np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [40]:
ar. sum( axis=0)

array([6, 8, 9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  2])

In [42]:
ar.T

array([[1, 4, 1],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
1
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.shape

(3, 3)

In [48]:
ar.nbytes

72

In [49]:
one = np.array([1,2,34,4,])

In [50]:
one.argmax()

np.int64(2)

In [51]:
ar[2]

array([1, 1, 0])

In [52]:
one[2]

np.int64(34)

In [53]:
one.argmin()

np.int64(0)

In [54]:
one[0]

np.int64(1)

In [55]:
one.argsort()

array([0, 1, 3, 2])

In [56]:
i = {0,1,3,2}
for j in i:
    print(one[j])

1
2
34
4


In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [58]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [59]:
print(ar.argmax(),ar.argmin())

5 8


In [60]:
ar.argmax(axis=0)

array([1, 1, 1])

In [61]:
ar.argmax(axis=1)

array([2, 2, 0])

In [62]:
print("arg method gives the indeces for the required methods")

arg method gives the indeces for the required methods


In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 1, 1, 0])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [65]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [1],
       [1],
       [0]])

In [66]:
ar2= np.array([[1,2,3],[3,4,5],[4,5,6]])

In [67]:
ar2.shape

(3, 3)

In [68]:
ar.shape

(3, 3)

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [70]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [1.        , 1.        , 0.        ]])

In [71]:
ar.sum()

np.int64(23)

In [72]:
ar.max()

np.int64(6)

In [73]:
ar.min()

np.int64(0)

In [74]:
np.where(ar>2)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [76]:
np.where(ar>2)
'''
this will give the indeces row*column wise
'''


'\nthis will give the indeces row*column wise\n'

In [77]:
n1=np.array([2,3,4,5])

In [78]:
type(np.where(n1>1))

tuple

In [79]:
np.count_nonzero(n1)

np.int64(4)

In [80]:
np.nonzero(n1)

(array([0, 1, 2, 3]),)

In [81]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [82]:
np.count_nonzero(ar)

np.int64(8)

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [84]:
import sys


In [85]:
py_ar=[3,4,5,6,76,7]

In [87]:
npa_ar=np.array(py_ar)

In [89]:
sys.getsizeof(1)* len(py_ar)

168

In [92]:
npa_ar.itemsize * npa_ar.size

48