In [1]:
import numpy as np
import numpy.polynomial.polynomial  as poly

## random numbers creations

In [2]:
np.random.rand(3)


array([0.33105643, 0.75081912, 0.66517888])

In [3]:
np.random.randn(3)

array([ 0.1722957 , -0.49277129,  1.61057883])

In [4]:
np.random.randint(0,10,12) # here start,stop, number_of_random_values

array([0, 0, 0, 2, 3, 3, 9, 7, 2, 2, 9, 7], dtype=int32)

In [5]:
for i in range(10):
    options=np.random.choice(['anshu','aman','junu','anu'])
    print(options)

anu
anshu
anu
anu
anu
aman
aman
junu
anu
anu


### polynomials

In [6]:
eqn = poly.Polynomial([2,0,4])


In [7]:
print(eqn)

2.0 + 0.0 x + 4.0 x**2


### meshGrid

In [8]:
x=np.arange(1,10,2)
y=np.arange(2,20,4)
X,Y =np.meshgrid(x,y)

In [9]:
x = np.linspace(-5, 5, 5)
y = np.linspace(-5, 5, 5)
xx, yy = np.meshgrid(x, y)

z = np.sin(xx**2 + yy**2)
print("Z values:\n", z)

Z values:
 [[-0.26237485 -0.16516621 -0.13235175 -0.16516621 -0.26237485]
 [-0.16516621 -0.0663219  -0.03317922 -0.0663219  -0.16516621]
 [-0.13235175 -0.03317922  0.         -0.03317922 -0.13235175]
 [-0.16516621 -0.0663219  -0.03317922 -0.0663219  -0.16516621]
 [-0.26237485 -0.16516621 -0.13235175 -0.16516621 -0.26237485]]


TypeError: 'numpy.int64' object is not iterable

# array creation 


In [ ]:
np.array([1,2,3,4,3])

In [ ]:
np.zeros(5)

In [ ]:
np.eye(3)

In [ ]:
np.arange(0,10,2)

In [ ]:
np.arange(2,10,3)

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.random.rand(4) # this will create the random numbers (0,1)

# Araay Attributes

In [ ]:
arr=np.array([[1,2,4,5],[67,34,23,2],[2,3,4,4]])

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr.ndim

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr[[0,0],[2,3]] #this will take row from the first and the columns from the second pair

# indexing and slicing

In [ ]:
arr

In [ ]:
arr[2,3]

In [ ]:
arr[:,0]

In [ ]:
arr[0,:]

In [ ]:
arr[0:1,:2]

# operations in array 

In [ ]:
a=np.array([1,2,3,4])
b=np.array([3,45,6,7])
a+b

In [ ]:
print(a)
print(b)
print(a+b)

In [ ]:
print(np.sqrt(a))

In [ ]:
np.dot(a,b)

# reshaping and transpoing

In [ ]:
anshu=np.arange(6)

In [ ]:
anshu.reshape(2,3) #the eventual products of the seperate = to the total of the numbers

In [ ]:
reshaped=anshu.reshape(3,2)

In [ ]:
print(reshaped)

In [ ]:
reshaped.T

In [ ]:
reshaped.flatten()  #flatten is the reverse of the reshape 'flatten' is the attribute

# concatanation & Splittingg

In [ ]:
np.array([[2,3,4],[2,4,5]])

In [ ]:
np.array([[[2,3,4],[6,7,8]]]) # ndim = n*[ ]

In [ ]:
a=np.array([[1,2],[3,4]])
b = np.array([[5,4],[6,8]])
concat=np.concatenate((a,b),axis=0)
np.vstack((a,b))
np.hstack((a,b))

# broadcasting - ### arithematics operations on arrays with different shape

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print("")

print(a+b)

# universal functions

In [ ]:
anshu=np.array([[2,3],[3,7]])

In [ ]:
np.power(anshu,2)

In [ ]:
np.sin(arr)

In [ ]:
arr = np.array([1, 2, 3, -1, -2])
masked = np.ma.masked_where(arr < 0, arr)

print("Masked mean:", masked.mean())


# Tier -3

#### linear algerae

In [ ]:
a=np.array([[2,3],[7,8]])
b=np.array([[2,8],[56,8]])

In [ ]:
a@b # this is for the matrix multiplications

In [ ]:
np.linalg.inv(a)

In [ ]:
np.linalg.det(a)

In [ ]:
np.linalg.eig(a)

#### fancy indexing

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

In [ ]:
arr[[2,0],[0,1]]

#### savinf and loading arrays

In [ ]:
kripa=np.arange(10)
np.save('saved',kripa)

In [ ]:
np.savetxt('numedpytest',kripa)